Conversion from ASM8080 to ASL
While I was searching for images of CP/M 2.2, I came across
ASM source files for CCP and BDOS, and an assembler that
produces binaries matching the CP/M 2.2 distribution.

    https://github.com/brouhaha/cpm22.git
    http://john/cacc/rwth-aachen.de:8000/as/

I installed {AS} on my development system, verified that the
ASM files assemble and look sane, fiddled a bit with setting
the memory size, then imported the ASM files here.

Change to VoidStar8080.c:
- for now, B is like A, and D is like C.

Changes needed to my ASM files:
- add ".CPU 8080" directives at the top
- register pairs are H (not HL), D (not DE), and B (not BC)
- trailing "," on DB lines are not allowed

Note on the DRI "DISKDEF" library:
- need to construct labels by pasting the value of a counter
  with a base name. I have not worked out how to get ASL
  to do this (it might be impossible), so some Python code
  is appropriate to generate the result. Will use DRI's assembler
  once we have a CP/M system working. Normally, you would
  hard code IBM Single Density in your initial CBIOS then use
  the CP/M tools to assemble the full CBIOS later.

  I'm being stubborn and setting up my CBIOS to have DPBs
  for two IBM Single Density diskettes and two big hard drives.


The RETTEST file had some Rcc instructions that had
erroneous arguments remaining from the conversion
from the CALL test to the RET test. Fix it up,

Interesting:
- ASM8080 interpreted "DB 'X'+80h" as placing an 'X'
  followed by an 80h byte. This was not apparent until I
  compared the outputs of ASM8080 and ASL for FORTH,
  so it is good that I had not attempted to run FORTH.

  This impacted the ROM test: it loaded data from the FORTH
  hex file into ROM and printed it; so, with the change in the
  output to correct the last byte of every NAME field, this output
  was completely different. Updated expected text to contain
  the proper data from the revised FORTH assembly.

Also:
- VoidStar8080 periodically reports the "simtime-to-rtctime" ratio
- add a separate build target to run the (void*)8080 simulation
- remove the duplicate symbol in AXG.ASM,
- be consistant about colons on labels in ASM files
- oops, need to track the IMG files for the RST and STACK tests.
- oops, need a "lst/.gitignore" file like the ones in hex and elsewhere
- oops, do not track the EMACS backup of a .gitignore file